USE accountingMaterials;

CREATE TABLE Materials
(
	ID INT NOT NULL PRIMARY KEY,
	Name VARCHAR(150) NOT NULL,
	Number INT NOT NULL,
	Price MONEY
);

CREATE TABLE Employee
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Position VARCHAR(100) NOT NULL 
);

CREATE TABLE Unit
(
	ID INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL
);

CREATE TABLE ManufacturingCost
(
	ID INT NOT NULL PRIMARY KEY,
	NAME VARCHAR(60) NOT NULL
);

CREATE TABLE DebtAct
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	UnitID INT NOT NULL,
	MaterialCount INT NOT NULL,
	EmployeeID INT NOT NULL,
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID),
	FOREIGN KEY (UnitID) REFERENCES Unit(ID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(ID)
);

CREATE TABLE RequiementAct
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	UnitID INT NOT NULL,
	RequiredCount INT NOT NULL,
	ReleasedCount INT NOT NULL,
	EmployeeID INT NOT NULL,
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID),
	FOREIGN KEY (UnitID) REFERENCES Unit(ID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(ID)
);

CREATE TABLE Timecards
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	Data DATE NOT NULL,
	DocumentNumber INT NOT NULL,
	FromWhom VARCHAR(50) NOT NULL,
	Income INT NOT NULL,
	Outcome INT NOT NULL, 
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID)
);

CREATE TABLE Waybill
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	UnitID INT NOT NULL,
	RequiredCount INT NOT NULL,
	ReleasedCount INT NOT NULL,
	EmployeeID INT NOT NULL,
	DocumentNumber INT NOT NULL,
	Data DATE NOT NULL,
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID),
	FOREIGN KEY (UnitID) REFERENCES Unit(ID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(ID)
);

CREATE TABLE UseInProduction
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	UnitID INT NOT NULL,
	Remains INT NOT NULL,
	RequiredCount INT NOT NULL,
	ActualRise INT NOT NULL,
	EmployeeID INT NOT NULL,
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID),
	FOREIGN KEY (UnitID) REFERENCES Unit(ID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(ID)
);

CREATE TABLE UseOfMatrials
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	UnitID INT NOT NULL,
	MaterialCount INT NOT NULL,
	ManufacturingCostID INT NOT NULL,
	EmployeeID INT NOT NULL,
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID),
	FOREIGN KEY (UnitID) REFERENCES Unit(ID),
	FOREIGN KEY (ManufacturingCostID) REFERENCES ManufacturingCost(ID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(ID)
);

CREATE TABLE RequirementInvoice
(
	ID INT NOT NULL PRIMARY KEY,
	MaterialID INT NOT NULL,
	UnitID INT NOT NULL,
	RequiredCount INT NOT NULL,
	ReleasedCount INT NOT NULL,
	EmployeeID INT NOT NULL,
	DocumentNumber INT NOT NULL,
	Data DATE NOT NULL,
	FOREIGN KEY (MaterialID) REFERENCES Materials(ID),
	FOREIGN KEY (UnitID) REFERENCES Unit(ID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(ID)
);