USE accountingMaterials;

CREATE TABLE MaterialsHistory
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MaterialId INT NOT NULL,
    Operation NVARCHAR(200) NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
);

CREATE TABLE EmployeeHistory
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	EmployeeId INT NOT NULL,
    Operation NVARCHAR(200) NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
);

CREATE TABLE UnitHistory
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	UnitId INT NOT NULL,
    Operation NVARCHAR(200) NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
);

CREATE TABLE ManufacturingCostHistory
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ManufacturingCostId INT NOT NULL,
    Operation NVARCHAR(200) NOT NULL,
	CreateAt DATETIME NOT NULL DEFAULT GETDATE(),
);